### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by yocontra** [TorchlightSoftware/mongo-watch#1]
Do you have any benchmarks/perf tests?

**Comment by bitmage** [comment]
Nope.  I'm about to create a load test using chats as an example.  It shouldn't be hard to make a low level test along with that.  If there are any specific metrics you're looking for let me know and I'll include them in my testing.

**Comment by kof** [comment]
There ARE performance issues, I recently started to use mubsub and run into several of them:

https://github.com/scttnlsn/mubsub/issues/9

https://github.com/scttnlsn/mubsub/issues/15

https://github.com/mongodb/node-mongodb-native/issues/963

https://jira.mongodb.org/browse/NODE-42

**Comment by bitmage** [comment]
This is ambiguous and depends very much on what you're doing.  Closing unless someone comes up with a more specific case.
