### ISSUE TITLE
Lodash dependency in package.json

### ISSUE THREAD

**Issue by TheInsomniac** [TorchlightSoftware/mongo-watch#11]
By default lodash is only a dependency in DevDependencies but it, appears to be, a requirement for production as well.

With just your simple example on github / npm I get unmet dependencies for lodash until such time as I install it.

**Comment by TheInsomniac** [comment]
Darn. I see it's already been merged but not to the NPM repo..
Closed!

**Comment by bitmage** [comment]
Sorry about that.  It's pushed out now as 0.2.6.
